name: CD.yml
on:
  push:
    branches:
      - prod
      - dev
    
jobs:
      DeployToAWS:
        
        runs-on: ubuntu-latest
        
        permissions:
          
          id-token: write
          contents: read
        
        environment: 
                    
          name: ${{ github.ref_name }}
          
        steps:
          
          - uses: actions/checkout@v2
            
          - name: Setup AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-region: ${{ secrets.AWS_REGION }}
              role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
              role-session-name: github-action
              
          - name: Setting stage and stack name
            run: |
              echo "STAGE=${{ github.ref_name }}" 
              echo "STACK_NAME=LockLairStackAuth${{github.ref_name}}" >> $GITHUB_ENV
              
          - uses: actions/checkout@v3
          
          - name: Install .NET and CDK
            run: | 
              npm install -g aws-cdk
              dotnet --version
              dotnet workload install wasm-tools # se necessário
              dotnet tool restore
              
          - name: Restore & Build CDK Project
            run: |
              cd iac
              dotnet restore
              dotnet build

          - name: CDK Synth
            run: |
              cd iac
              cdk synth

          - name: CDK Deploy
            run: |
              cd iac
              cdk deploy --require-approval never
            env:
              AWS_REGION: ${{ vars.AWS_REGION }}
              AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
              STACK_NAME: ${{ env.STACK_NAME }}
              GITHUB_REF_NAME: ${{ github.ref_name }} 
          
          
        