name: CI

on:
  
  push:
    branches:
      - master
      - dev
      - prod
      
  pull_request: 
    branches:
      - dev
      - prod
        
jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Compile project
        run: dotnet build --no-restore
        
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
